[options]
#logfile = /opt/odoo-17.0/logs/odoo.log
admin_passwd = $pbkdf2-sha512$600000$eW9NyfkfI.S81zrH2HuP8Q$BdActSzM.yEYCR7sR6UCmVpktSYSUqcQSjkv35tCGkjuLex5bNuYCroMHFrY.uSJMT7SSksUkJb857/0BcXSmg
db_password = odoo
db_user = odoo
addons_path = /opt/odoo-17.0/odoo/odoo/addons,/opt/odoo-17.0/odoo/addons,/opt/odoo-17.0/custom_addons,/opt/odoo-17.0/pjts/learn
db_host = localhost
db_port = False
data_dir = /opt/odoo-17.0/data
log_handler = werkzeug:WARN,:INFO
